# Generated by Django 4.2.3 on 2023-08-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Room_Name',
            field=models.CharField(max_length=122),
        ),
    ]
